### Dev Environment ###

server:
  port: 9019

spring:

  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: ""
    driver-class-name: "com.mysql.jdbc.Driver"

  redis:
    host: localhost
    port: 6379